const e=(channel,text,payment)=>({channel,text,...(payment?{payment}:{} )});
const pay=(amount,newPayee=true)=>e('payment','',{amount,newPayee});
export const scenarios=[
{id:'refund-qr',name:'The refund that sends money',family:'Refund / QR reversal',scam:true,description:'A cashback message becomes an outgoing QR payment.',events:[e('message','Receive your refund of 2500. Scan the QR to receive money.'),e('qr','upi://pay?pa=refunddesk@demo&pn=Refund%20Desk&am=2500&cu=INR'),pay(2500)]},
{id:'digital-arrest',name:'An officer. A threat. A transfer.',family:'Authority / digital arrest',scam:true,description:'A controlled call transcript leads to a new beneficiary.',events:[e('call','I am a CBI officer. A criminal warrant has been issued.'),e('call','Do not disconnect. Do not tell your family. Transfer to a safe account.'),pay(40000)]},
{id:'investment',name:'Small deposit, larger promise',family:'Investment escalation',scam:true,description:'An investment promise escalates from 500 to 50000.',events:[e('message','Join our institutional IPO group. Guaranteed return and sure profit.'),e('link','https://trading-demo.invalid/trading.apk'),e('call','Deposit 500 to begin trading with us.'),pay(500),e('message','Your profit is ready. Transfer a larger deposit now.'),pay(50000)]},
{id:'job-task',name:'Pay to unlock your earnings',family:'Task / advance fee',scam:true,description:'A task reward becomes a fee to withdraw.',events:[e('message','Your work is complete. Pay the task deposit.'),e('message','Pay the withdrawal fee to unlock earnings.'),pay(8000)]},
{id:'remote-support',name:'Support wants your screen',family:'Remote access support',scam:true,description:'A refund pretext leads to remote control.',events:[e('call','Your refund is pending. I am your bank official.'),e('message','Install AnyDesk and enable remote access to receive your refund.'),pay(5000)]},
{id:'kyc',name:'A KYC request for a secret',family:'Credential theft',scam:true,description:'A banking threat leads to an OTP request.',events:[e('message','Your account will be blocked immediately for KYC.'),e('link','https://kyc-demo.invalid'),e('message','Share your OTP to complete verification.')]},
{id:'courier',name:'Courier customs pressure',family:'Authority / digital arrest',scam:true,holdout:true,description:'An unseen courier pretext reuses authority and payment tactics.',events:[e('call','Customs officer here. Your illegal parcel has been intercepted.'),e('message','Transfer a processing payment immediately.'),pay(18000)]},
{id:'family-emergency',name:'An emergency with secrecy',family:'Pressure to transfer',scam:true,holdout:true,description:'A simulated family emergency tests tactic composition.',events:[e('call','Urgent. Stay on the call. Keep this secret.'),e('message','Send money immediately.'),pay(12000)]},
{id:'hinglish',name:'Hinglish payment pressure',family:'Pressure to transfer',scam:true,description:'A transliterated Hindi account threat precedes UPI.',events:[e('message','Account band ho jayega. Jaldi karo abhi. Kisi ko mat batana.'),e('message','Paise bhejo UPI se.'),pay(22000)]},
{id:'hindi-refund',name:'Hindi refund reversal',family:'Refund / QR reversal',scam:true,description:'Hindi refund copy followed by an outgoing QR.',events:[e('message','आपके पैसे वापस मिलेंगे। यह रिफंड है।'),e('qr','upi://pay?pa=testrefund@demo&am=1800&cu=INR'),pay(1800)]},
{id:'otp-advice',name:'A real security reminder',scam:false,description:'Negation must prevent an OTP warning.',events:[e('message','Your bank will never ask for your OTP. Never share your PIN or password.'),pay(1200,false)]},
{id:'restaurant',name:'Paying for lunch',scam:false,description:'An ordinary merchant QR remains uninterrupted.',events:[e('message','Lunch was great. Here is the restaurant QR.'),e('qr','upi://pay?pa=lunchcafe@demo&pn=Lunch%20Cafe&am=480&cu=INR'),pay(480,false)]},
{id:'family',name:'Groceries for home',scam:false,description:'A new payment alone is not a scam.',events:[e('message','Mum please send 2000 for groceries.'),pay(2000)]},
{id:'salary',name:'Salary and rent',scam:false,description:'Routine financial context should not cause warnings.',events:[e('message','Your salary has been credited.'),e('message','Reminder to pay rent.'),pay(25000,false)]},
{id:'official-support',name:'Support keeps secrets private',scam:false,description:'Warnings about remote access are not requests.',events:[e('call','Do not share your OTP. Avoid remote access software.'),e('message','Contact your bank using its official number.')]},
{id:'market-risk',name:'An honest market disclaimer',scam:false,description:'Ordinary investment content is not guaranteed profit.',events:[e('message','This investment involves market risk. Returns vary.'),pay(10000,false)]},
{id:'school',name:'School invoice',scam:false,description:'A normal school payment stays quiet.',events:[e('message','Pay the school invoice through the official portal.'),pay(18000,false)]},
{id:'benign-urgent',name:'Urgent, but ordinary',scam:false,description:'Urgency plus payment alone is insufficient.',events:[e('message','Please pay the electricity bill today. It is urgent.'),pay(3000)]},
{id:'refund-complete',name:'A refund already credited',scam:false,description:'Receiving a refund without an outgoing action is passive.',events:[e('message','Refund credited to your original payment method.')]},
{id:'police-training',name:'Authority in a classroom',scam:false,description:'Mentioning police alone is insufficient.',events:[e('message','The training covers police and customs procedures.'),pay(800,false)]}
];
