// Development-only QA. Install Playwright and its browser, or set CHROMIUM_PATH.
import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('playwright');
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1100}});const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8000');await page.waitForSelector('#try-demo');
await page.screenshot({path:'test-results/protection-desktop.png',fullPage:true});
await page.click('#try-demo');await page.click('#next-event');assert.equal(await page.locator('#alert-card').isVisible(),false);
await page.click('#next-event');await page.click('#open-desk');assert.equal(await page.locator('#alert-card').isVisible(),true);
await page.click('#cancel-payment');assert.match(await page.locator('#decision-result').textContent(),/cancelled/);
await page.click('#continue-payment');await page.click('#confirm-continue');assert.match(await page.locator('#decision-result').textContent(),/continued/);
await page.screenshot({path:'test-results/refund-warning.png',fullPage:true});
await page.click('[data-view=privacy]');await page.click('#share-pattern');assert.match(await page.locator('#sharing-status').textContent(),/Choose/);
await page.check('#sharing-consent');await page.click('#share-pattern');await page.waitForFunction(()=>document.querySelector('#sharing-status').textContent.includes('Shared'));
await page.click('#delete-pattern');await page.waitForFunction(()=>document.querySelector('#sharing-status').textContent.includes('deleted'));
await page.check('#analytics-consent');await page.waitForFunction(()=>!document.querySelector('#analytics-consent').checked);
await page.click('[data-view=campaigns]');await page.click('#seed-campaigns');await page.waitForSelector('.campaign-card');assert.match(await page.locator('#campaign-list').textContent(),/UNVERIFIED/);
await page.click('[data-view=evaluation]');await page.waitForSelector('table');assert.equal(await page.locator('tbody tr').count(),20);
await page.click('[data-view=lab]');await page.click('[data-scenario=restaurant]');await page.click('#run-all');await page.click('#open-desk');assert.equal(await page.locator('#alert-card').isVisible(),false);
await page.fill('#content','Never share your OTP.');await page.click('#check-form button[type=submit]');assert.equal(await page.locator('#content').inputValue(),'');assert.equal(await page.locator('#alert-card').isVisible(),false);
await page.click('[data-channel=qr]');await page.fill('#content','upi://pay?pa=test@demo&am=NaN');await page.click('#check-form button[type=submit]');assert.match(await page.locator('#form-error').textContent(),/Amount/);
await page.setViewportSize({width:390,height:844});await page.click('#clear-session');await page.screenshot({path:'test-results/protection-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.waitForTimeout(500);await context.setOffline(true);await page.reload();await page.waitForSelector('#check-form');await page.fill('#content','Receive your refund');await page.click('#check-form button[type=submit]');assert.equal(await page.locator('#event-count').textContent(),'1 event');
assert.deepEqual(errors,[]);await writeFile('test-results/browser-summary.json',JSON.stringify({passed:true,checks:['desktop/mobile screenshots','pre-action passive behavior','QR warning','cancel and continuation','consent and deletion','analytics default off','campaign candidates','evaluation table','benign workflow','input clearing','invalid UPI','mobile overflow','offline reload'],errors},null,2));console.log('Browser QA passed: desktop, mobile, consent, warnings, campaign, and offline reload.');await browser.close();
