import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {pythonCommand} from '../scripts/python.mjs';
let pw;try{pw=createRequire(import.meta.url)('playwright');}catch{pw=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright/package.json')('playwright');}
await mkdir('test-results',{recursive:true});
const server=spawn(pythonCommand(),['backend/server.py','--port','8766','--db','test-results/reviews.sqlite'],{stdio:['ignore','pipe','inherit'],env:{...process.env,POSTHOG_PROJECT_TOKEN:''}});process.on('exit',()=>server.kill());await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);});
const browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote','--single-process']});
try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8766/app');await page.waitForSelector('#recent-list .empty-row');await page.click('.nav[data-view=protect]');
 await page.click('#review-call');assert.equal(await page.locator('#event-count').textContent(),'0 events');await page.click('#close-call');
 await page.click('[data-channel=link]');await page.fill('#content','Your SBI KYC is blocked. Visit https://sbi-verify.invalid immediately');await page.click('#check-form button[type=submit]');
 assert.match(await page.locator('#verification-evidence').textContent(),/MISMATCH|LOOKALIKE_IMPERSONATION/);assert.equal(await page.locator('#event-count').textContent(),'1 event');
 await page.click('#review-call');await page.check('#quick-signals input[value=authority]');await page.check('#quick-signals input[value=urgency]');await page.check('#quick-signals input[value=payment]');await page.click('#call-signals button[type=submit]');
 await page.click('[data-channel=call]');await page.fill('#content','Stay on the call. Do not tell your family. Transfer to a safe account.');await page.click('#check-form button[type=submit]');
 await page.click('[data-channel=payment]');await page.fill('#amount','40000');await page.check('#new-payee');await page.click('#check-form button[type=submit]');
 assert.equal(await page.locator('#event-count').textContent(),'4 events');assert(await page.locator('#alert-card').isVisible());
 await page.click('#paid-no');assert.match(await page.locator('#response-plan').textContent(),/Chakshu/);await page.click('#paid-yes');assert.match(await page.locator('#response-plan').textContent(),/1930/);assert.match(await page.locator('#response-plan').textContent(),/recovery/);
 await page.screenshot({path:'test-results/review-response-mobile.png',fullPage:true});
 await page.click('[data-view=reviews].nav');assert(await page.locator('.review-summary').count()>=1);await page.locator('#review-list .review-summary').first().click();assert.match(await page.locator('#response-plan').textContent(),/1930/);
 await page.click('#delete-review');assert.equal(await page.locator('#event-count').textContent(),'0 events');
 await page.click('[data-channel=call]');await page.fill('#content','Your bank will never ask you to share your OTP. Contact your bank independently.');await page.click('#check-form button[type=submit]');assert.equal(await page.locator('#alert-card').isVisible(),false);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 // Exercise native bridge using the exact packaged JS, without pretending this is a carrier test.
 await page.addInitScript(()=>{window.nativeSaved='';window.nativeRequests=[];window.NativeReviewMessages={postMessage(raw){const request=JSON.parse(raw);window.nativeRequests.push(request);if(request.method==='saveReviews')window.nativeSaved=request.payload;const result=request.method==='loadReviews'?window.seedReviews||'{}':true;queueMicrotask(()=>this.onmessage({data:JSON.stringify({id:request.id,result})}));}};window.deliverNative=payload=>window.NativeReviewMessages.onmessage({data:JSON.stringify({type:'native',payload})});});
 await page.reload();await page.waitForFunction(()=>typeof window.receiveNative==='function');
 assert.deepEqual(await page.evaluate(()=>window.nativeRequests.slice(0,2).map(r=>r.method)),['loadReviews','ready']);
 await page.evaluate(()=>window.deliverNative({kind:'call',id:'native-review-12345678',direction:'incoming'}));assert.equal(await page.locator('#event-count').textContent(),'0 events');await page.check('#quick-signals input[value=authority]');await page.check('#quick-signals input[value=urgency]');await page.click('#call-signals button[type=submit]');
 await page.evaluate(()=>window.deliverNative({kind:'share',text:'Stay on the call, send money to safe account'}));await page.waitForFunction(()=>document.querySelector('#content').value.includes('safe account'));assert.equal(await page.locator('#event-count').textContent(),'1 event');await page.click('#check-form button[type=submit]');assert.equal(await page.locator('#event-count').textContent(),'2 events');
 const image=(await readFile('simulator/fixtures/refund-qr.png')).toString('base64');await page.evaluate(image=>window.deliverNative({kind:'share',image,mime:'image/png'}),image);await page.waitForFunction(()=>document.querySelector('#content').value.startsWith('upi://'));assert.equal(await page.locator('#event-count').textContent(),'2 events');await page.click('#check-form button[type=submit]');assert.equal(await page.locator('#event-count').textContent(),'3 events');
 const state=JSON.parse(await page.evaluate(()=>window.nativeSaved));assert.equal(state.active,'native-review-12345678');assert.equal(state.reviews[0].timeline.at(-1).evidence_type,'screenshot');assert(!JSON.stringify(state).includes('fixture@demo'));
 await page.evaluate(()=>window.deliverNative({kind:'postcall'}));await page.click('#paid-yes');assert.match(await page.locator('#response-plan').textContent(),/1930/);
 await page.click('#report-review');await page.click('#share-pattern');assert.match(await page.locator('#sharing-status').textContent(),/Choose/);
 assert.deepEqual(errors,[]);await writeFile('test-results/review-browser-summary.json',JSON.stringify({passed:true,checks:['explicit call-review gate','submitted KYC mismatch and cross-channel escalation','paid and not-paid routes','review switching and deletion','normal call and payment','320–1440 layout','native bridge share and QR association without auto analysis','redacted snapshot','post-call response','report consent']},null,2));console.log('Review and native-bridge browser checks passed.');
}finally{await browser.close();server.kill();}
