"""Generate a self-contained 10-slide pitch + 3 architecture pages + 2 appendices."""
import json
from pathlib import Path
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
ROOT=Path(__file__).resolve().parents[1]
for name,file in [('Body','DejaVuSans.ttf'),('Bold','DejaVuSans-Bold.ttf'),('Title','DejaVuSerif.ttf')]:
    pdfmetrics.registerFont(TTFont(name,'/usr/share/fonts/truetype/dejavu/'+file))
W,H=1200,675
INK=HexColor('#192e2c');MUTED=HexColor('#687470');PAPER=HexColor('#f6f5ef');PEACH=HexColor('#e9a38a');LINE=HexColor('#d5d9cf')
OUT=ROOT/'docs/ScamGuard-RAKSHAM-Submission.pdf'
c=canvas.Canvas(str(OUT),pagesize=(W,H));c.setTitle('ScamGuard India - RAKSHAM problem 02');c.setAuthor('ScamGuard project; AI-assisted prototype')
m=json.loads((ROOT/'evaluation/results.json').read_text())
page=0
def para(text,x,y,width=490,size=16,color=INK):
    style=ParagraphStyle('p',fontName='Body',fontSize=size,leading=size*1.55,textColor=color)
    p=Paragraph(text,style);_,h=p.wrap(width,500);p.drawOn(c,x,y-h);return y-h-19
def base(section,title,subtitle=''):
    global page
    page+=1;c.setFillColor(PAPER);c.rect(0,0,W,H,fill=1,stroke=0)
    c.setFillColor(MUTED);c.setFont('Bold',11);c.drawString(58,H-42,'SCAMGUARD INDIA / RAKSHAM 2026');c.drawRightString(W-58,H-42,section)
    c.setFillColor(INK);c.setFont('Title',32);c.drawString(58,H-111,title)
    if subtitle:para(subtitle,58,H-137,W-116,14,MUTED)
    c.setStrokeColor(LINE);c.line(58,45,W-58,45);c.setFillColor(MUTED);c.setFont('Body',9);c.drawString(58,28,'Problem 02: AI-Driven Scam Pattern Recognition | Prototype evidence is synthetic unless explicitly stated');c.drawRightString(W-58,28,str(page))
def cards(left,right,y_start=H-207):
    for x,items in [(58,left),(635,right)]:
        y=y_start
        for title,body in items:
            y=para(title,x,y,507,18);y=para(body,x,y+6,507,14,MUTED)-12
def finish():c.showPage()
def box(x,y,w,h,title,body=''):
    c.setStrokeColor(LINE);c.setFillColor(HexColor('#fffef9'));c.roundRect(x,y,w,h,9,fill=1,stroke=1)
    next_y=para(title,x+18,y+h-18,w-36,15)
    if body:para(body,x+18,next_y+11,w-36,11,MUTED)
def arrow(x1,y1,x2,y2):
    import math
    c.setStrokeColor(MUTED);c.setLineWidth(1.4);c.line(x1,y1,x2,y2)
    a=math.atan2(y2-y1,x2-x1);c.line(x2,y2,x2-8*math.cos(a-.5),y2-8*math.sin(a-.5));c.line(x2,y2,x2-8*math.cos(a+.5),y2-8*math.sin(a+.5))

base('PITCH 01 / 10','A little pause. A lot of protection.','ScamGuard recognizes the financial scam workflow, then intervenes at a risky action.')
para('A scam is a journey, not just a suspicious caller.',58,455,700,29)
para('Messages, calls, links, QR codes and payment requests become one user-controlled local session. Behavior matters even when voices and scripts are generated by AI.',58,365,680,20,MUTED)
box(835,284,300,171,'USER-CONTROLLED','Check only when you choose. Local inference. No ordinary call recording. No banking credentials. No automatic blacklist.')
para('Working web reference prototype + a practical Android/PSP deployment path.<br/>This document contains 10 pitch slides, 3 architecture pages and 2 disclosure/reference appendices.',58,173,1000,13,MUTED);finish()
base('PITCH 02 / 10','The vulnerable moment is before money moves.','Primary user: a UPI user facing unfamiliar financial instructions, especially under time pressure.')
cards([('User need','A clear reason to pause, in plain language, without uploading an entire conversation.'),('Threat scenario','A plausible official voice, templated chat or investment promise moves the user from trust to secrecy, app installation, credentials and a transfer.')],[('Why single-channel checks miss context','A refund message can sound harmless; an outgoing QR is a normal payment primitive. Together they contradict the promise of receiving money.'),('Scope and limits','Targets scam behavior irrespective of AI origin. It does not prove a voice is cloned, inspect arbitrary bank apps, or intercept ordinary cellular-call audio.')]);finish()
base('PITCH 03 / 10','A refund message becomes an outgoing payment.','Synthetic demonstration: the warning is attached to the harmful transition.')
box(58,320,330,170,'01 / MESSAGE','“Receive your refund. Scan this QR to receive money.” Local context records a refund claim; no interruption yet.')
box(435,320,330,170,'02 / UPI INTENT','upi://pay payload resolves to an outgoing payment. Parsed payee and exact amount are immediately discarded; only a bucket remains.')
box(812,320,330,170,'03 / PAUSE','Refund claim + outgoing intent triggers an explanation before simulated authorization. Cancel or independently verify.')
arrow(390,405,432,405);arrow(767,405,809,405)
para('Ordinary counterexample: a restaurant QR and known merchant context proceed without a warning. Every decision uses the same engine.',58,265,1060,18)
para('No money moves. Calls are typed/consented transcripts. QR screenshots and optional camera frames decode locally using native detection or bundled jsQR. Text sharing uses a private PWA POST target.',58,161,1060,13,MUTED);finish()
base('PITCH 04 / 10','Small local models. Explicit workflow logic.','The phone-facing path stays light; server connectivity is not required for a local warning.')
cards([('Tier 0: cheap extraction','NFKC/invisible-control normalization, thirteen tactic rules, negated-advice handling and strict UPI intent parsing.'),('Tier 1: compact AI support','Eleven binary word/bigram logistic heads. 157 disclosed synthetic training texts. Exported JSON model: '+str(round(m['model_bytes']/1024))+' KiB. No hosted LLM.')],[('Temporal session','User chooses one active conversation; at most 64 derived events; 20-minute inactivity expiry. Ordered pretext-to-action patterns plus coarse payment escalation.'),('Guarded decisions','An action-aware gate needs a matched workflow and independent signals, or a direct request for a secret. ML corroboration contributes at most 3 points and cannot warn alone.')]);finish()
base('PITCH 05 / 10','Warning less is part of protecting better.','Suspicion and action risk are separate heuristic indices, not calibrated probabilities.')
cards([('Passive before an action','Suspicious wording alone adds context. Evidence remains visible without interrupting the user.'),('Useful at the transition','Explain what happened: a refund led to an outgoing QR, authority and threat led to transfer, or a request sought secret credentials.')],[('Limit repetition','60-second suppression. Re-warn for a different matched workflow, increased severity, a new sensitive action, or a financial increase of at least two amount buckets.'),('Human agency','Cancel the simulated request or confirm continuation after a second review. The product never promises safety from a low score. Feedback is not automatic retraining.')]);finish()
base('PITCH 06 / 10','New patterns become candidates for review.','Emerging workflows are an intelligence problem, not a licence to blacklist people.')
cards([('Minimum data','User separately consents to sharing tactic/channel enums, sequence, amount bucket, count and a random session ID. No transcript, VPA, audio or exact amount.'),('Implemented discovery baseline','Jaccard >=0.70 plus ordered LCS >=0.70. Three session reports create a candidate. Two fixed 20-report windows provide a Hoeffding distribution-shift cue.')],[('Human review','Token-gated analyst marks a candidate reviewed or dismissed. No candidate changes the local warning policy or labels a payment account as fraudulent.'),('Research extension','A synthetic shift (20 ordinary then 20 new-composition reports) is detected. The bound assumes independent reports; identities are unverified. Compare HDBSCAN/ADWIN after reporter trust is established.')]);finish()
base('PITCH 07 / 10','Validation that names its limits.','20 smoke + 32 later AI-authored challenge workflows. No real-world accuracy or real-phone performance claim.')
for x,label,value,detail in [(58,'SCAM WORKFLOWS WARNED',f"{m['true_positive']} / {m['scam_sessions']}",'Includes two known misses'),(343,'ORDINARY INTERRUPTIONS',f"{m['false_positive']} / {m['legitimate_sessions']}",'Curated ordinary cases'),(628,'PRE-PAYMENT COVERAGE',f"{m['prepayment_rate']*100:.1f}%",'15 / 17 synthetic payment scams'),(913,'ENGINE P95',f"{m['latency_ms']['p95']:.3f} ms",'Linux container; not a phone')]:
    box(x,344,230,146,label);para(value,x+18,432,200,29);para(detail,x+18,380,200,11,MUTED)
cards([('Current checks','29 automated tests: negation, Unicode evasion, ordered timing, stale-session reset, UPI ambiguity, warning upgrade, PII exclusion, consent, deletion, retention and analyst gate.')],[('Open evidence gaps','Two known misses: indirect coercion and implicit yield. Rules and hybrid warn on the same 24 cases, so no ML recall improvement is claimed. Test licensed traffic, family/time splits and actual phone latency/battery.')],y_start=300)
# Place cards below metric panels without colliding with them.
finish()
base('PITCH 08 / 10','Privacy is an implementation constraint.','Data minimization does not mean “risk free”: fingerprints and consent remain sensitive.')
cards([('Default off','Camera only after user activation, for QR scanning. No microphone, notifications, SMS, call-log or banking access. Pattern sharing and usage analytics are separate visit-only opt-ins. All local checks work without analytics.'),('Bounded retention','Derived local session stays in memory; raw input clears after analysis. Shared fingerprints expire after 24 hours; an opaque session ID enables deletion.')],[('Security controls','Localhost binding, bounded JSON, enum allowlists, request limits, same-origin validation, CSP, static route containment and no content access logs.'),('Known limits','Prototype reports are not identity-verified. Browser memory and SQLite pages do not guarantee forensic erasure. Public deployment needs TLS, authenticated reporters, quotas, audit controls and security review.')]);finish()
base('PITCH 09 / 10','Start with sharing. Integrate before authorization.','Adoption pathway: give the user control now; deepen protection only with authorised access.')
cards([('Today: usable reference MVP','Phone-first PWA; private POST share target; local QR images/camera; ML/rules; 52-scenario lab; ordered campaign inbox; redacted exports; opt-in PostHog.'),('Next: native Android','Sharesheet and QR adapters. User-triggered controlled VoIP with consented LiveKit/sherpa audio. Typed transcripts remain a reliable demo fallback.')],[('Partner pathway','Bank/PSP/wallet sandbox sends PaymentEvent before authorization. Same lightweight engine returns contextual warning and user review; it does not scrape other apps.'),('Scale deliberately','Move local SQLite reference service to authenticated ingestion and durable encrypted storage. Add validated drift/clustering and reviewed signed policy snapshots. Keep graph models off the phone hot path.')]);finish()
base('PITCH 10 / 10','A credible 48-hour build, with a baseline already working.','2-4 students; combine app/UX and engine/validation roles for a two-person team.')
for y,label,body in [(462,'00-12 HOURS','Reproduce baseline; lock data contracts and test suite; build Android share/QR adapter if tooling is ready.'),(379,'12-24 HOURS','Complete payment simulator + local warning trace; optional consented VoIP/ASR with typed fallback; verify deletion and logs.'),(296,'24-38 HOURS','Rules/hybrid ablation; independent paraphrases; poisoning tests; real-device timing; accessibility and consented usability.'),(213,'38-48 HOURS','Freeze versions; disclose AI/data/assets; rehearse refund + investment + benign QR; prepare a backup runnable build.')]:
    para(label,58,y,220,14);para(body,310,y,820,15,MUTED)
para('Success targets to test, not claim: <300 ms P95 payment warning on a midrange device; <2 interruptions per 100 independently labelled legitimate flows; >90% representative pre-payment intervention.',58,113,1080,12,MUTED);finish()
base('ARCHITECTURE 01 / 03','End-to-end system and trust boundaries.','Solid arrows are implemented. Future audio/Android/PSP adapters enter the same event contract.')
box(58,374,230,114,'USER / LOCAL INPUT','Message, link, typed call, decoded QR, simulated payment')
box(354,374,230,114,'LOCAL CASCADE','Normalization, rules and exported word/bigram model')
box(650,374,230,114,'SESSION + POLICY','Ordered evidence, action gate, bounded state and suppression')
arrow(289,433,352,433);arrow(585,433,648,433)
box(933,374,209,114,'USER WARNING','Explain, cancel, verify or explicitly continue simulation');arrow(882,433,931,433)
box(650,172,230,114,'PATTERN SHARING','Enums and amount bucket; no raw text or personal identifiers');arrow(765,372,765,288)
box(354,172,230,114,'LOCAL CAMPAIGN API','Strict schema, SQLite expiry, deduplication and candidate grouping');arrow(648,229,586,229)
box(58,172,230,114,'HUMAN REVIEW','Analyst token; reviewed/dismissed status; no policy publication');arrow(352,229,290,229)
para('Separate optional analytics path: explicit user opt-in -> coarse allowlisted events -> configured PostHog transport. Failure never delays protection. Production requires authenticated reporters and a signed threat-update boundary.',58,117,1080,12,MUTED);finish()
base('ARCHITECTURE 02 / 03','Detection, data flow and intervention policy.','A deterministic rule-led cascade with bounded ML corroboration makes the decision reviewable.')
cards([('Input and feature contract','One event: channel, text or simulated payment, monotonic timestamp. Parse locally. Retain only tactic enums, model scores, derived coarse payment information and timing.'),('Workflow matching','Refund -> outgoing QR; authority + pressure -> transfer; guarantee -> escalating investment payment; fee-to-unlock; remote-control support; direct credential request. Ordered pretext checks prevent arbitrary keyword pooling.')],[('Gate and output','No risky action: quiet/watch. Matched action + sufficient independent signals: warning/high. Repeat suppress for 60s unless risk increases. Return reason, stage, evidence index, action-risk index and a user choice.'),('Fingerprint schema','version; random session_id; tactic set; ordered tactic sequence; channel set; amount_bucket; event_count. Maximum 64 events. Unknown fields, raw content and non-enum strings are rejected.')]);finish()
base('ARCHITECTURE 03 / 03','Review, escalation and operational safeguards.','No automatic blocking, threat-policy publication or fraud-account identification in the prototype.')
cards([('Candidate -> review','Distinct random session reports cluster by tactic and ordered-sequence similarity. Fixed 20/20 windows expose a shift cue under independence assumptions. Three reports create an unverified candidate. Analyst auth is required to mark reviewed or dismissed. A reviewed candidate is not proof of fraud.'),('User escalation path','Pause; contact the institution through independently sourced official details; export the redacted report. In a real suspected financial fraud, use official reporting channels. Automated external reporting is not implemented.')],[('Abuse and security','Sybil/poisoning threat is explicit. Rate limiting and deduplication are only baseline controls. Public rollout must add reporter trust, device/session attestation where appropriate, encrypted storage, auditability and red-team validation.'),('Privacy lifecycle','Raw input never enters API, analytics or cache. Fixed public app assets alone are cached offline. User-controlled report deletion; 24-hour server expiry. Granular consent; no SDK autocapture, replay or person profiles.')]);finish()
base('APPENDIX A / OPTIONAL','AI and asset disclosure.','All synthetic assets and models are labelled; no confidential customer or bank data is used.')
cards([('AI-generated content','ChatGPT/Codex generated code, documentation, visual design, SVG shield, synthetic text/scenarios and this PDF under user direction. Human review is required before contest submission.'),('Datasets and model','157 AI-authored training texts; 52 workflows (26 scam, 26 ordinary), including 32 later challenge fixtures. Two indirect scams are known misses. Eleven scikit-learn logistic heads; no ASR, deepfake or graph model ships.')],[('Third-party runtime and tools','Python/SQLite; browser APIs; bundled jsQR 1.4.0 (Apache-2.0); Node tests. scikit-learn 1.8.0 for training (BSD-3-Clause); ReportLab for PDF (BSD); Playwright for development checks; official GitHub actions. Optional PostHog capture API.'),('Visual and research assets','System font stacks in app; DejaVu fonts embedded in PDF; original generated SVG. No bank/company logos or stock imagery. Earlier pasted research statistics are not reproduced as independently verified results. All data/model artefacts are in the repository.')]);finish()
base('APPENDIX B / OPTIONAL','References and reproducibility.','This PDF stands alone. Links below are operational references, not required to understand the proposal.')
y=475
for text in ['Android: developer.android.com/reference/android/telecom/CallScreeningService','NPCI: npci.org.in/safety-feature','scikit-learn: scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html','PostHog: posthog.com/docs/api/capture and /docs/product-analytics/capture-events','Mobile QR/share: bundled jsQR 1.4.0 (Apache-2.0); MDN Web App Manifest share_target.',
'Reproduce: python3 backend/server.py; npm test; npm run evaluate; npm run qa.','Source: github.com/1shu1iwari-crypto/AI-Protect (feat/scamguard-mobile-workflows).','Before upload: add actual team names/eligibility details and independently verify organiser requirements. No contest registration or submission has been performed.']:
    y=para(text,58,y,1080,14,MUTED)
finish();c.save();print(OUT)
