import {Session,parseUPI} from '/core/engine.mjs';
import {scenarios as originalScenarios} from '/simulator/scenarios.mjs';
import {challenges} from '/simulator/challenges.mjs';
import {CameraScanner,decodeImage} from '/web/qr.mjs';
const scenarios=[...originalScenarios,...challenges];
import {Analytics} from '/web/analytics.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let model=null;try{model=await(await fetch('/core/model.json')).json();}catch{}
const session=new Session(model),analytics=new Analytics();let channel='message',selected=scenarios[0],step=0,lastResult=null,lastLatency=0,toastTimer,sharedIds=new Set(),replayBusy=false;
const names={protect:'Protection desk',lab:'Scenario lab',campaigns:'Campaign inbox',evaluation:'Validation',privacy:'Privacy controls'};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function view(name){camera.stop();$('#camera-dialog').close();document.documentElement.dataset.view=name;for(const v of $$('.view'))v.hidden=v.id!=='view-'+name;for(const b of $$('[data-view]'))b.classList.toggle('active',b.dataset.view===name);$('#page-name').textContent=names[name];if(name==='privacy')renderFingerprint();if(name==='campaigns')refreshCampaigns();if(name==='evaluation')evaluation();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function reset(){camera.stop();$('#camera-dialog').close();session.reset();lastResult=null;step=0;$('#content').value='';$('#payee').value='';$('#form-error').textContent='';$('#sharing-consent').checked=false;$('#sharing-status').textContent='';$('#alert-card').hidden=true;$('#decision-result').textContent='';$('#replay-output').replaceChildren();render();renderScenario();toast('Session cleared. Local checks are ready.');}
$('#clear-session').onclick=reset;$('#privacy-clear').onclick=reset;
const help={message:['Paste a message you want to check','Only content you submit is checked. Text is cleared after analysis.','Your refund is ready. Scan this QR to receive money…'],link:['Paste a suspicious link','The link is inspected as text. ScamGuard never opens the destination.','https://example.invalid/support.apk'],qr:['Paste the decoded UPI QR payload','An upi://pay intent sends money. Payee details are parsed locally and discarded.','upi://pay?pa=merchant@demo&am=2500&cu=INR'],call:['Paste a consented call transcript','Typed transcript only. This prototype does not listen to calls or request microphone access.','I am a police officer. Do not disconnect. Transfer to a safe account.']};
function setChannel(c){camera.stop();$('#camera-dialog').close();channel=c;for(const b of $$('[data-channel]')){b.classList.toggle('selected',b.dataset.channel===c);b.setAttribute('aria-selected',String(b.dataset.channel===c));}$('#payment-input').hidden=c!=='payment';$('#text-input').hidden=c==='payment';$('#qr-import').hidden=c!=='qr';$('#form-error').textContent='';if(help[c]){$('#input-label').textContent=help[c][0];$('#input-help').textContent=help[c][1];$('#content').placeholder=help[c][2];}$('#content').value='';}
$$('[data-channel]').forEach(b=>b.onclick=()=>setChannel(b.dataset.channel));
function check(input,source='user_check'){const start=performance.now();const r=session.add(input);lastLatency=performance.now()-start;lastResult=r;render();analytics.capture('check_completed',{severity:r.severity,stage:r.stage,latency_ms:lastLatency,channel:input.channel,source,intervention:r.showWarning?'shown':r.suppressed?'suppressed':'none'});if(r.suppressed)analytics.capture('warning_suppressed',{severity:r.severity,stage:r.stage,source});if(r.showWarning){$('#alert-card').hidden=false;$('#alert-title').textContent='This request needs a pause.';$('#alert-reason').textContent=r.reason;$('#decision-result').textContent='';analytics.capture('warning_shown',{severity:r.severity,stage:r.stage,latency_ms:lastLatency,source});if(!$('#view-protect').hidden){$('#alert-card').focus({preventScroll:true});$('#alert-card').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}return r;}
$('#check-form').onsubmit=ev=>{ev.preventDefault();try{let input={channel,text:$('#content').value};if(channel==='payment')input={channel,payment:{amount:Number($('#amount').value),newPayee:$('#new-payee').checked}};else if(!input.text.trim())throw Error('Paste content before checking.');check(input);$('#content').value='';$('#payee').value='';$('#form-error').textContent='';toast(lastResult.showWarning?'Pause and verify this request.':'Context checked locally.');}catch(e){$('#form-error').textContent=e.message;}};
function render(){const count=session.events.length;$('#event-count').textContent=count+' event'+(count===1?'':'s');$('#session-empty').hidden=count>0;$('#session-result').hidden=!count;$('#export-session').disabled=!count;if(lastResult){$('#evidence').innerHTML=lastResult.evidenceScore+'<span>/100</span>';$('#risk').innerHTML=lastResult.actionRisk+'<span>/100</span>';$('#risk-bar').style.width=lastResult.actionRisk+'%';$('#stage').textContent=lastResult.stage;$('#severity').textContent=lastResult.suppressed?'Repeated warning limited':lastResult.severity.toUpperCase();$('#result-note').textContent=lastResult.reason;$('#latency').textContent='Last local check: '+lastLatency.toFixed(1)+' ms';$('#timeline').innerHTML=session.events.map((e,i)=>'<div class="timeline-item"><strong>'+String(i+1).padStart(2,'0')+' / '+escape(e.channel.toUpperCase())+'</strong><span>'+escape(e.tactics.join(' · ')||'No tactic evidence')+'</span></div>').join('');}else{$('#timeline').replaceChildren();$('#latency').textContent='Waiting for your first check';}renderFingerprint();}
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#export-session').onclick=()=>download('scamguard-redacted-report.json',{prototype:true,fingerprint:session.fingerprint(),assessment:lastResult?{family:lastResult.family,severity:lastResult.severity,stage:lastResult.stage,reason:lastResult.reason}:null});
$('#cancel-payment').onclick=()=>{$('#decision-result').textContent='Simulated request cancelled. No money has moved.';analytics.capture('user_cancelled_payment',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#continue-payment').onclick=()=>$('#continue-dialog').showModal();$('#keep-paused').onclick=()=>$('#continue-dialog').close();$('#confirm-continue').onclick=()=>{$('#continue-dialog').close();$('#decision-result').textContent='Simulated request continued by your choice. No real transaction occurred.';analytics.capture('user_continued',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#false-positive').onclick=()=>{$('#decision-result').textContent='Feedback recorded for this visit. The detection policy has not been changed.';analytics.capture('false_positive_feedback',{severity:lastResult?.severity,stage:lastResult?.stage});};
function renderScenarios(){$('#scenario-list').innerHTML=scenarios.map(s=>'<button class="scenario-item '+(s.id===selected.id?'active':'')+'" data-scenario="'+s.id+'"><span>'+(s.scam?'SCAM SIMULATION':'ORDINARY WORKFLOW')+(s.holdout?' · HOLDOUT':'')+'</span><strong>'+escape(s.name)+'</strong></button>').join('');$$('[data-scenario]').forEach(b=>b.onclick=()=>{if(replayBusy)return;selected=scenarios.find(s=>s.id===b.dataset.scenario);reset();renderScenarios();});}
function renderScenario(){$('#scenario-type').textContent=selected.scam?'SYNTHETIC SCAM SCENARIO':'SYNTHETIC ORDINARY WORKFLOW';$('#scenario-name').textContent=selected.name;$('#scenario-description').textContent=selected.description;$('#step-count').textContent=step+' / '+selected.events.length;const e=selected.events[step];$('#replay-preview').innerHTML=e?'<small>NEXT / '+escape(e.channel.toUpperCase())+'</small><p>'+escape(e.payment?'Prepare a simulated ₹'+e.payment.amount.toLocaleString('en-IN')+' transfer'+(e.payment.newPayee?' to a new beneficiary.':'.'):e.text)+'</p>':'<small>STORY COMPLETE</small><p>'+(selected.scam?'Review the warning and evidence at the protection desk.':'An ordinary workflow checked without inventing a scam verdict.')+'</p>';$('#next-event').disabled=!e;$('#run-all').disabled=!e;}
function next(){if(step>=selected.events.length)return;const r=check({...selected.events[step],timestamp:session.started-(selected.events.length-step)*20000},selected.scam?'synthetic_scam':'synthetic_benign');step++;const div=document.createElement('div');div.className='replay-result'+(r.showWarning?' warning':'');div.innerHTML='<b>'+step+' / '+escape(r.event.channel.toUpperCase())+' · '+(r.showWarning?'WARNING':r.suppressed?'REPEAT LIMITED':r.severity.toUpperCase())+'</b><br>'+escape(r.reason);$('#replay-output').append(div);renderScenario();}
$('#next-event').onclick=next;$('#run-all').onclick=()=>{replayBusy=true;try{while(step<selected.events.length)next();}finally{replayBusy=false;}};$('#restart-demo').onclick=reset;$('#try-demo').onclick=()=>{selected=scenarios[0];reset();renderScenarios();view('lab');};$('#open-desk').onclick=()=>view('protect');
async function api(path,body,method='POST',headers={}){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const p=await r.json();if(!r.ok)throw Error(p.error||'Request failed');return p;}
function renderFingerprint(){$('#fingerprint-preview').textContent=JSON.stringify(session.fingerprint(),null,2);}
$('#share-pattern').onclick=async()=>{try{if(!$('#sharing-consent').checked)throw Error('Choose to share this pattern first.');if(!session.events.length)throw Error('Check at least one event first.');await api('/api/fingerprints',{consent:true,fingerprint:session.fingerprint()});sharedIds.add(session.id);$('#sharing-status').textContent='Shared with the local campaign service. Retained for at most 24 hours.';analytics.capture('user_reported_scam');}catch(e){$('#sharing-status').textContent=e.message;}};
$('#delete-pattern').onclick=async()=>{try{if(!sharedIds.size)throw Error('No pattern has been shared during this visit.');for(const id of [...sharedIds]){await api('/api/fingerprints/'+encodeURIComponent(id),null,'DELETE');sharedIds.delete(id);}$('#sharing-status').textContent='Your shared patterns were deleted.';}catch(e){$('#sharing-status').textContent=e.message;}};
$('#analytics-consent').onchange=async()=>{await analytics.load();analytics.enable($('#analytics-consent').checked);if(!analytics.enabled)$('#analytics-consent').checked=false;$('#analytics-status').textContent=analytics.enabled?'Anonymous usage events enabled for this visit.':'Analytics are off. The operator must configure a PostHog project token to enable them.';if(analytics.enabled)analytics.capture('scamguard_activated');};
async function refreshCampaigns(){try{const {campaigns}=await(await fetch('/api/campaigns')).json();$('#campaign-list').innerHTML=campaigns.length?campaigns.map(g=>'<section class="card campaign-card"><div><div class="eyebrow">'+escape(g.status.toUpperCase())+' · UNVERIFIED REPORTS</div><h2>'+escape(g.composition)+'</h2><div class="chips">'+g.tactics.map(t=>'<span>'+escape(t)+'</span>').join('')+'</div><p>'+escape(g.method)+'. Unverified reporters; no payee data collected.</p><div class="sequence-line">'+g.sequence.map(escape).join(' → ')+'</div>'+(g.shift.detected?'<div class="shift-note"><b>Distribution shift candidate</b><p>'+g.shift.baseline_count+'/20 previous reports → '+g.shift.recent_count+'/20 recent reports. Independent-reporter assumptions remain unverified.</p></div>':'<p class="help">'+(g.shift.enough_data?'No distribution shift detected in the last two windows.':'40 total reports needed for a two-window shift check.')+'</p>')+'<p class="help">Candidate formed after 3 reports · '+g.seconds_to_candidate.toFixed(1)+' seconds in this local replay.</p><div class="review-actions"><button class="outline" data-review="reviewed" data-signature="'+escape(g.signature)+'">Mark reviewed</button> <button class="text-button" data-review="dismissed" data-signature="'+escape(g.signature)+'">Dismiss candidate</button></div></div><div class="campaign-count">'+g.reports+'<small>CONSENTED PATTERNS</small></div></section>').join(''):'<div class="card"><h2>No candidates yet.</h2><p>Share consenting test-session patterns, or generate synthetic reports. Three similar reports create a candidate for review.</p></div>';$$('[data-review]').forEach(b=>b.onclick=async()=>{try{await api('/api/review',{signature:b.dataset.signature,status:b.dataset.review},'POST',{Authorization:'Bearer '+$('#review-token').value});$('#review-token').value='';refreshCampaigns();toast('Candidate review saved. No threat policy was published.');}catch(e){toast(e.message);}});}catch{$('#campaign-list').innerHTML='<div class="card"><h2>The campaign service is unavailable.</h2><p>Local protection still works. Start the Python server to review patterns.</p></div>';}}
$('#refresh-campaigns').onclick=refreshCampaigns;$('#seed-campaigns').onclick=async()=>{try{for(let i=0;i<5;i++){const s=new Session(model);const scenario=scenarios.find(s=>s.id==='investment');for(const [j,e] of scenario.events.entries())s.add({...e,timestamp:s.started+j*20000});await api('/api/fingerprints',{consent:true,fingerprint:s.fingerprint()});}$('#campaign-status').textContent='5 AI-authored synthetic session fingerprints added.';refreshCampaigns();}catch(e){$('#campaign-status').textContent=e.message;}};
async function evaluation(){try{const m=await(await fetch('/evaluation/results.json')).json();$('#evaluation-content').innerHTML='<div class="metrics-grid">'+[['Scam workflows warned',m.true_positive+'/'+m.scam_sessions,'Synthetic workflow recall'],['Legitimate interruptions',m.false_positive+'/'+m.legitimate_sessions,'Synthetic benign flows'],['Pre-payment coverage',Math.round(m.prepayment_rate*100)+'%','Only payment scam scenarios'],['P95 engine latency',m.latency_ms.p95.toFixed(2)+' ms',m.environment]].map(([a,b,c])=>'<div class="card metric-card"><span class="metric-label">'+escape(a)+'</span><strong>'+escape(b)+'</strong><p>'+escape(c)+'</p></div>').join('')+'</div><div class="card table-scroll"><table><caption>Every workflow, disclosed</caption><thead><tr><th>SCENARIO</th><th>EXPECTED</th><th>WARNING</th><th>FIRST WARNING STAGE</th></tr></thead><tbody>'+m.scenarios.map(s=>'<tr><td>'+escape(s.name)+'</td><td>'+(s.scam?'Scam':'Ordinary')+'</td><td>'+(s.warned?'Yes':'No')+'</td><td>'+escape(s.first_warning_stage||'—')+'</td></tr>').join('')+'</tbody></table><p class="help">Generated '+escape(m.generated_at)+'. Scores are deterministic heuristic indices. The 157-text model is experimental support only. The workflow engine makes the warning decision.</p></div>';}catch{$('#evaluation-content').innerHTML='<div class="card"><p>Run npm run evaluate to produce the reproducible evaluation report.</p></div>';}}
const camera=new CameraScanner($('#camera-video'),value=>{try{parseUPI(value);$('#content').value=value;$('#camera-dialog').close();toast('QR read locally. Choose Check to inspect it.');}catch(e){$('#camera-dialog').close();$('#form-error').textContent=e.message;}},message=>$('#camera-status').textContent=message);
$('#qr-file').onchange=async ev=>{const file=ev.target.files[0];try{if(!file)return;const value=await decodeImage(file);parseUPI(value);$('#content').value=value;$('#form-error').textContent='';toast('QR decoded locally. Tap Check to inspect the payment intent.');}catch(e){$('#form-error').textContent=e.message;}finally{ev.target.value='';}};
$('#scan-camera').onclick=async()=>{$('#camera-dialog').showModal();try{await camera.start();}catch(e){camera.stop();$('#camera-status').textContent=e.name==='NotAllowedError'?'Camera permission was declined. Use a screenshot or paste the QR payload.':e.message;}};
$('#stop-camera').onclick=()=>{camera.stop();$('#camera-dialog').close();};
$('#camera-dialog').addEventListener('close',()=>camera.stop());
$('#camera-dialog').addEventListener('cancel',()=>camera.stop());
document.addEventListener('visibilitychange',()=>{if(document.hidden){camera.stop();$('#camera-dialog').close();}});
window.addEventListener('pagehide',()=>camera.stop());
$('#seed-emergence').onclick=async()=>{const button=$('#seed-emergence');button.disabled=true;try{for(let i=0;i<40;i++){const s=new Session(model);if(i<20)s.add({channel:'message',text:'Urgent: please pay the electricity bill today.'});else{s.add({channel:'call',text:'I am a bank officer. Do not tell anyone.'});s.add({channel:'message',text:'Install our app to enable remote access.'});}s.add({channel:'payment',payment:{amount:4500,newPayee:i>=20}});await api('/api/fingerprints',{consent:true,fingerprint:s.fingerprint()});$('#campaign-status').textContent=(i+1)+'/40 synthetic reports replayed';}await refreshCampaigns();toast('20 ordinary reports followed by 20 new-composition reports. Review the shift cue.');}catch(e){$('#campaign-status').textContent=e.message;}finally{button.disabled=false;}};
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app').hidden=false;});
$('#install-app').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('#install-app').hidden=true;};
$$('[data-channel]').forEach((button,i,buttons)=>button.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].focus();setChannel(buttons[j].dataset.channel);}));
async function receiveSharedContent(){
 const match=location.hash.match(/^#shared=([a-zA-Z0-9-]{8,64})$/);if(!match)return;
 history.replaceState(null,'',location.pathname);
 try{await navigator.serviceWorker.ready;const worker=navigator.serviceWorker.controller;if(!worker)throw Error('Paste the shared content to check it.');
 const payload=await new Promise((resolve,reject)=>{const channel=new MessageChannel();const timer=setTimeout(()=>{channel.port1.close();reject(Error('Shared content expired. Paste it again.'));},4000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();resolve(e.data);};worker.postMessage({type:'TAKE_SHARE',token:match[1]},[channel.port2]);});
 if(payload.error)throw Error(payload.error);setChannel('message');$('#content').value=payload.text;toast('Shared content is ready. You choose when to check it.');
 }catch(e){toast(e.message);}
}
render();renderScenarios();renderScenario();$('#scenario-total').textContent=scenarios.length;
window.addEventListener('offline',()=>$('#connectivity').textContent='● Offline local checks');window.addEventListener('online',()=>$('#connectivity').textContent='● On-device engine');
if('serviceWorker' in navigator){navigator.serviceWorker.register('/web/sw.js',{scope:'/'}).then(receiveSharedContent).catch(()=>{});}
