import {ReviewSession,QUICK_SIGNALS,signalText,responsePlan} from '/core/review.mjs';
import {Session,parseUPI,LABELS} from '/core/engine.mjs';
import {scenarios as originalScenarios} from '/simulator/scenarios.mjs';
import {challenges} from '/simulator/challenges.mjs';
import {CameraScanner,decodeImage} from '/web/qr.mjs';
const scenarios=[...originalScenarios,...challenges];
import {Analytics} from '/web/analytics.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pendingShared=false;let pendingEvidenceType=null;
let model=null;try{model=await(await fetch('/core/model.json')).json();}catch{}
let session=new ReviewSession(model);const reviews=new Map();const analytics=new Analytics();let channel='message',selected=scenarios[0],step=0,lastResult=null,lastLatency=0,toastTimer,sharedIds=new Set(),replayBusy=false;
const names={protect:'Check',reviews:'Reviews',lab:'Scenario lab',campaigns:'Campaign inbox',evaluation:'Validation',privacy:'Privacy controls'};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function view(name){camera.stop();$('#camera-dialog').close();document.documentElement.dataset.view=name;for(const v of $$('.view'))v.hidden=v.id!=='view-'+name;for(const b of $$('[data-view]'))b.classList.toggle('active',b.dataset.view===name);$('#page-name').textContent=names[name];if(name==='reviews')renderReviews();if(name==='privacy')renderFingerprint();if(name==='campaigns')refreshCampaigns();if(name==='evaluation')evaluation();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function reset(){camera.stop();$('#camera-dialog').close();reviews.delete(session.id);session.reset();lastResult=null;step=0;$('#content').value='';$('#payee').value='';$('#form-error').textContent='';$('#sharing-consent').checked=false;$('#sharing-status').textContent='';$('#alert-card').hidden=true;$('#action-center').hidden=true;$('#response-plan').replaceChildren();$('#decision-result').textContent='';$('#replay-output').replaceChildren();render();renderScenario();toast('Session cleared. Local checks are ready.');}
$('#clear-session').onclick=reset;$('#privacy-clear').onclick=reset;
const help={message:['Paste a message you want to check','Only content you submit is checked. Text is cleared after analysis.','Your refund is ready. Scan this QR to receive money…'],link:['Paste a suspicious link','The link is inspected as text. ScamGuard never opens the destination.','https://example.invalid/support.apk'],qr:['Paste the decoded UPI QR payload','An upi://pay intent sends money. Payee details are parsed locally and discarded.','upi://pay?pa=merchant@demo&am=2500&cu=INR'],call:['Paste a consented call transcript','Typed transcript only. This prototype does not listen to calls or request microphone access.','I am a police officer. Do not disconnect. Transfer to a safe account.']};
function setChannel(c){camera.stop();$('#camera-dialog').close();channel=c;for(const b of $$('[data-channel]')){b.classList.toggle('selected',b.dataset.channel===c);b.setAttribute('aria-selected',String(b.dataset.channel===c));}$('#payment-input').hidden=c!=='payment';$('#text-input').hidden=c==='payment';$('#qr-import').hidden=c!=='qr';$('#form-error').textContent='';if(help[c]){$('#input-label').textContent=help[c][0];$('#input-help').textContent=help[c][1];$('#content').placeholder=help[c][2];}$('#content').value='';}
$$('[data-channel]').forEach(b=>b.onclick=()=>setChannel(b.dataset.channel));
function check(input,source='user_check'){const start=performance.now();const r=session.add({...input,userTriggered:true});lastLatency=performance.now()-start;lastResult=r;render();analytics.capture('check_completed',{severity:r.severity,stage:r.stage,latency_ms:lastLatency,channel:input.channel,source,intervention:r.showWarning?'shown':r.suppressed?'suppressed':'none'});if(r.suppressed)analytics.capture('warning_suppressed',{severity:r.severity,stage:r.stage,source});if(r.showWarning){$('#alert-card').hidden=false;$('#alert-title').textContent='STOP & VERIFY';$('#alert-reason').textContent=r.reason;$('#decision-result').textContent='';analytics.capture('warning_shown',{severity:r.severity,stage:r.stage,latency_ms:lastLatency,source});if(!$('#view-protect').hidden){$('#alert-card').focus({preventScroll:true});$('#alert-card').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}return r;}
$('#check-form').onsubmit=ev=>{ev.preventDefault();try{let input={channel,text:$('#content').value,evidence_type:pendingEvidenceType};if(channel==='payment')input={channel,payment:{amount:Number($('#amount').value),newPayee:$('#new-payee').checked}};else if(!input.text.trim())throw Error('Paste content before checking.');check(input);pendingShared=false;pendingEvidenceType=null;$('#content').value='';$('#payee').value='';$('#form-error').textContent='';toast(lastResult.showWarning?'Pause and verify this request.':'Context checked locally.');}catch(e){$('#form-error').textContent=e.message;}};
function render(){renderReviewDetails();const count=session.events.length;$('#event-count').textContent=count+' event'+(count===1?'':'s');$('#session-empty').hidden=count>0;$('#session-result').hidden=!count;$('#export-session').disabled=!count;if(lastResult){$('#evidence').innerHTML=lastResult.evidenceScore+'<span>/100</span>';$('#risk').innerHTML=lastResult.actionRisk+'<span>/100</span>';$('#risk-bar').style.width=lastResult.actionRisk+'%';$('#stage').textContent=lastResult.stage;$('#severity').textContent=lastResult.suppressed?'Repeated warning limited':lastResult.severity.toUpperCase();$('#result-note').textContent=lastResult.reason;$('#latency').textContent='Last local check: '+lastLatency.toFixed(1)+' ms';$('#timeline').innerHTML=session.timeline.map((e,i)=>'<div class="timeline-item"><strong>'+String(i+1).padStart(2,'0')+' / '+escape(e.channel.toUpperCase())+' · '+escape(e.change)+'</strong><span>Verification: '+escape(e.verification)+' · '+escape(e.evidence.map(t=>LABELS[t]||t).join(' · ')||'No tactic evidence')+'</span><p>'+escape(e.reason)+'</p></div>').join('');}else{$('#timeline').replaceChildren();$('#latency').textContent='Waiting for your first check';}renderFingerprint();}
function download(name,value){if(window.NativeReview){window.NativeReview.exportReport(JSON.stringify(value));return;}const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#export-session').onclick=exportReview;
$('#cancel-payment').onclick=()=>{session.recordAction('cancel_simulation');persistReviews();$('#decision-result').textContent='Simulated request cancelled. No money has moved.';analytics.capture('user_cancelled_payment',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#continue-payment').onclick=()=>$('#continue-dialog').showModal();$('#keep-paused').onclick=()=>$('#continue-dialog').close();$('#confirm-continue').onclick=()=>{session.recordAction('continue_simulation');persistReviews();$('#continue-dialog').close();$('#decision-result').textContent='Simulated request continued by your choice. No real transaction occurred.';analytics.capture('user_continued',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#false-positive').onclick=()=>{$('#decision-result').textContent='Feedback recorded for this visit. The detection policy has not been changed.';analytics.capture('false_positive_feedback',{severity:lastResult?.severity,stage:lastResult?.stage});};
function renderScenarios(){$('#scenario-list').innerHTML=scenarios.map(s=>'<button class="scenario-item '+(s.id===selected.id?'active':'')+'" data-scenario="'+s.id+'"><span>'+(s.scam?'SCAM SIMULATION':'ORDINARY WORKFLOW')+(s.holdout?' · HOLDOUT':'')+'</span><strong>'+escape(s.name)+'</strong></button>').join('');$$('[data-scenario]').forEach(b=>b.onclick=()=>{if(replayBusy)return;selected=scenarios.find(s=>s.id===b.dataset.scenario);reset();renderScenarios();});}
function renderScenario(){$('#scenario-type').textContent=selected.scam?'SYNTHETIC SCAM SCENARIO':'SYNTHETIC ORDINARY WORKFLOW';$('#scenario-name').textContent=selected.name;$('#scenario-description').textContent=selected.description;$('#step-count').textContent=step+' / '+selected.events.length;const e=selected.events[step];$('#replay-preview').innerHTML=e?'<small>NEXT / '+escape(e.channel.toUpperCase())+'</small><p>'+escape(e.payment?'Prepare a simulated ₹'+e.payment.amount.toLocaleString('en-IN')+' transfer'+(e.payment.newPayee?' to a new beneficiary.':'.'):e.text)+'</p>':'<small>STORY COMPLETE</small><p>'+(selected.scam?'Review the warning and evidence at the protection desk.':'An ordinary workflow checked without inventing a scam verdict.')+'</p>';$('#next-event').disabled=!e;$('#run-all').disabled=!e;}
function next(){if(step>=selected.events.length)return;const r=check({...selected.events[step],timestamp:session.started-(selected.events.length-step)*20000},selected.scam?'synthetic_scam':'synthetic_benign');step++;const div=document.createElement('div');div.className='replay-result'+(r.showWarning?' warning':'');div.innerHTML='<b>'+step+' / '+escape(r.event.channel.toUpperCase())+' · '+(r.showWarning?'WARNING':r.suppressed?'REPEAT LIMITED':r.severity.toUpperCase())+'</b><br>'+escape(r.reason);$('#replay-output').append(div);renderScenario();}
$('#next-event').onclick=next;$('#run-all').onclick=()=>{replayBusy=true;try{while(step<selected.events.length)next();}finally{replayBusy=false;}};$('#restart-demo').onclick=reset;$('#try-demo').onclick=()=>{selected=scenarios[0];reset();renderScenarios();view('lab');};$('#open-desk').onclick=()=>view('protect');
async function api(path,body,method='POST',headers={}){if(window.NativeReview)throw Error('Campaign sharing needs the web app and local server. Export this redacted review instead.');const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const p=await r.json();if(!r.ok)throw Error(p.error||'Request failed');return p;}
function renderFingerprint(){$('#fingerprint-preview').textContent=JSON.stringify(session.fingerprint(),null,2);}
$('#share-pattern').onclick=async()=>{try{if(!$('#sharing-consent').checked)throw Error('Choose to share this pattern first.');if(!session.events.length)throw Error('Check at least one event first.');session.consent=$('#sharing-consent').checked;await api('/api/fingerprints',session.report());sharedIds.add(session.id);$('#sharing-status').textContent='Shared with the local campaign service. Retained for at most 24 hours.';analytics.capture('user_reported_scam');}catch(e){$('#sharing-status').textContent=e.message;}};
$('#delete-pattern').onclick=async()=>{try{if(!sharedIds.size)throw Error('No pattern has been shared during this visit.');for(const id of [...sharedIds]){await api('/api/fingerprints/'+encodeURIComponent(id),null,'DELETE');sharedIds.delete(id);}$('#sharing-status').textContent='Your shared patterns were deleted.';}catch(e){$('#sharing-status').textContent=e.message;}};
$('#analytics-consent').onchange=async()=>{await analytics.load();analytics.enable($('#analytics-consent').checked);if(!analytics.enabled)$('#analytics-consent').checked=false;$('#analytics-status').textContent=analytics.enabled?'Anonymous usage events enabled for this visit.':'Analytics are off. The operator must configure a PostHog project token to enable them.';if(analytics.enabled)analytics.capture('scamguard_activated');};
async function refreshCampaigns(){if(window.NativeReview){$('#campaign-list').innerHTML='<div class="card"><h2>Campaign review is on the local web server.</h2><p>This Android companion has no network permission. Export a redacted review for your own records; no report is uploaded from this app.</p></div>';return;}try{const {campaigns}=await(await fetch('/api/campaigns')).json();$('#campaign-list').innerHTML=campaigns.length?campaigns.map(g=>'<section class="card campaign-card"><div><div class="eyebrow">'+escape(g.status.toUpperCase())+' · UNVERIFIED REPORTS</div><h2>'+escape(g.composition)+'</h2><div class="chips">'+g.tactics.map(t=>'<span>'+escape(t)+' · '+(g.tactic_frequency?.[t]??g.reports)+' reports</span>').join('')+'</div><p>'+escape(g.method)+'. Unverified reporters; no payee data collected.</p><div class="sequence-line">'+g.sequence.map(escape).join(' → ')+'</div>'+(g.shift.detected?'<div class="shift-note"><b>Distribution shift candidate</b><p>'+g.shift.baseline_count+'/20 previous reports → '+g.shift.recent_count+'/20 recent reports. Independent-reporter assumptions remain unverified.</p></div>':'<p class="help">'+(g.shift.enough_data?'No distribution shift detected in the last two windows.':'40 total reports needed for a two-window shift check.')+'</p>')+'<p class="help">Candidate formed after 3 reports · '+g.seconds_to_candidate.toFixed(1)+' seconds in this local replay.</p><div class="review-actions"><button class="outline" data-review="reviewed" data-signature="'+escape(g.signature)+'">Mark reviewed</button> <button class="text-button" data-review="dismissed" data-signature="'+escape(g.signature)+'">Dismiss candidate</button></div></div><div class="campaign-count">'+g.reports+'<small>CONSENTED PATTERNS</small></div></section>').join(''):'<div class="card"><h2>No candidates yet.</h2><p>Share consenting test-session patterns, or generate synthetic reports. Three similar reports create a candidate for review.</p></div>';$$('[data-review]').forEach(b=>b.onclick=async()=>{try{await api('/api/review',{signature:b.dataset.signature,status:b.dataset.review},'POST',{Authorization:'Bearer '+$('#review-token').value});$('#review-token').value='';refreshCampaigns();toast('Candidate review saved. No threat policy was published.');}catch(e){toast(e.message);}});}catch{$('#campaign-list').innerHTML='<div class="card"><h2>The campaign service is unavailable.</h2><p>Local protection still works. Start the Python server to review patterns.</p></div>';}}
$('#refresh-campaigns').onclick=refreshCampaigns;$('#seed-campaigns').onclick=async()=>{try{for(let i=0;i<5;i++){const s=new Session(model);const scenario=scenarios.find(s=>s.id==='investment');for(const [j,e] of scenario.events.entries())s.add({...e,timestamp:s.started+j*20000});await api('/api/fingerprints',{consent:true,fingerprint:s.fingerprint()});}$('#campaign-status').textContent='5 AI-authored synthetic session fingerprints added.';refreshCampaigns();}catch(e){$('#campaign-status').textContent=e.message;}};
async function evaluation(){try{const m=await(await fetch('/evaluation/results.json')).json();$('#evaluation-content').innerHTML='<div class="metrics-grid">'+[['Scam workflows warned',m.true_positive+'/'+m.scam_sessions,'Synthetic workflow recall'],['Legitimate interruptions',m.false_positive+'/'+m.legitimate_sessions,'Synthetic benign flows'],['Pre-payment coverage',Math.round(m.prepayment_rate*100)+'%','Only payment scam scenarios'],['P95 engine latency',m.latency_ms.p95.toFixed(2)+' ms',m.environment]].map(([a,b,c])=>'<div class="card metric-card"><span class="metric-label">'+escape(a)+'</span><strong>'+escape(b)+'</strong><p>'+escape(c)+'</p></div>').join('')+'</div><div class="card table-scroll"><table><caption>Every workflow, disclosed</caption><thead><tr><th>SCENARIO</th><th>EXPECTED</th><th>WARNING</th><th>FIRST WARNING STAGE</th></tr></thead><tbody>'+m.scenarios.map(s=>'<tr><td>'+escape(s.name)+'</td><td>'+(s.scam?'Scam':'Ordinary')+'</td><td>'+(s.warned?'Yes':'No')+'</td><td>'+escape(s.first_warning_stage||'—')+'</td></tr>').join('')+'</tbody></table><p class="help">Generated '+escape(m.generated_at)+'. Scores are deterministic heuristic indices. The 157-text model is experimental support only. The workflow engine makes the warning decision.</p></div>';}catch{$('#evaluation-content').innerHTML='<div class="card"><p>Run npm run evaluate to produce the reproducible evaluation report.</p></div>';}}
const camera=new CameraScanner($('#camera-video'),value=>{try{parseUPI(value);$('#content').value=value;$('#camera-dialog').close();toast('QR read locally. Choose Check to inspect it.');}catch(e){$('#camera-dialog').close();$('#form-error').textContent=e.message;}},message=>$('#camera-status').textContent=message);
$('#qr-file').onchange=async ev=>{const file=ev.target.files[0];try{if(!file)return;const value=await decodeImage(file);parseUPI(value);$('#content').value=value;$('#form-error').textContent='';toast('QR decoded locally. Tap Check to inspect the payment intent.');}catch(e){$('#form-error').textContent=e.message;}finally{ev.target.value='';}};
$('#scan-camera').onclick=async()=>{$('#camera-dialog').showModal();try{await camera.start();}catch(e){camera.stop();$('#camera-status').textContent=e.name==='NotAllowedError'?'Camera permission was declined. Use a screenshot or paste the QR payload.':e.message;}};
$('#stop-camera').onclick=()=>{camera.stop();$('#camera-dialog').close();};
$('#camera-dialog').addEventListener('close',()=>camera.stop());
$('#camera-dialog').addEventListener('cancel',()=>camera.stop());
document.addEventListener('visibilitychange',()=>{if(document.hidden){camera.stop();$('#camera-dialog').close();}});
window.addEventListener('pagehide',()=>camera.stop());
$('#seed-emergence').onclick=async()=>{const button=$('#seed-emergence');button.disabled=true;try{for(let i=0;i<40;i++){const s=new Session(model);if(i<20)s.add({channel:'message',text:'Urgent: please pay the electricity bill today.'});else{s.add({channel:'call',text:'I am a bank officer. Do not tell anyone.'});s.add({channel:'message',text:'Install our app to enable remote access.'});}s.add({channel:'payment',payment:{amount:4500,newPayee:i>=20}});await api('/api/fingerprints',{consent:true,fingerprint:s.fingerprint()});$('#campaign-status').textContent=(i+1)+'/40 synthetic reports replayed';}await refreshCampaigns();toast('20 ordinary reports followed by 20 new-composition reports. Review the shift cue.');}catch(e){$('#campaign-status').textContent=e.message;}finally{button.disabled=false;}};
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app').hidden=false;});
$('#install-app').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('#install-app').hidden=true;};
$$('[data-channel]').forEach((button,i,buttons)=>button.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].focus();setChannel(buttons[j].dataset.channel);}));
async function receiveSharedContent(){
 const match=location.hash.match(/^#shared=([a-zA-Z0-9-]{8,64})$/);if(!match)return;
 history.replaceState(null,'',location.pathname);
 try{await navigator.serviceWorker.ready;const worker=navigator.serviceWorker.controller;if(!worker)throw Error('Paste the shared content to check it.');
 const payload=await new Promise((resolve,reject)=>{const channel=new MessageChannel();const timer=setTimeout(()=>{channel.port1.close();reject(Error('Shared content expired. Paste it again.'));},4000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();resolve(e.data);};worker.postMessage({type:'TAKE_SHARE',token:match[1]},[channel.port2]);});
 if(payload.error)throw Error(payload.error);if(payload.review){try{session=ReviewSession.restore(payload.review,model);lastResult=session.events.length?session.assess(session.events.at(-1)):null;render();}catch{}}setChannel(payload.text.trim().startsWith('upi://')?'qr':'message');pendingShared=true;$('#content').value=payload.text;toast('Shared content is ready. You choose when to check it.');
 }catch(e){toast(e.message);}
}
initializeReviews();render();renderScenarios();renderScenario();$('#scenario-total').textContent=scenarios.length;
window.addEventListener('offline',()=>$('#connectivity').textContent='● Offline local checks');window.addEventListener('online',()=>$('#connectivity').textContent='● On-device engine');
if('serviceWorker' in navigator&&!window.NativeReview){navigator.serviceWorker.register('/web/sw.js',{scope:'/'}).then(receiveSharedContent).catch(()=>{});}

function persistReviews(){
 if(session.events.length||session.user_flagged)reviews.set(session.id,session.snapshot());
 while(reviews.size>10)reviews.delete(reviews.keys().next().value);
 const state=JSON.stringify({active:session.id,reviews:[...reviews.values()]});
 window.NativeReview?.saveReviews(state);
 navigator.serviceWorker?.controller?.postMessage({type:'REVIEW_CONTEXT',review:session.events.length?session.snapshot():null});
}
function initializeReviews(){
 if(!window.NativeReview)return;
 for(const id of ['seed-campaigns','seed-emergence','analytics-consent','scan-camera'])$('#'+id).disabled=true;
 $('#analytics-status').textContent='Android companion: no network permission; analytics are unavailable.';
 try{const state=JSON.parse(window.NativeReview.loadReviews()||'{}');for(const r of state.reviews||[]){try{const restored=ReviewSession.restore(r,model);reviews.set(restored.id,restored.snapshot());}catch{}}if(reviews.has(state.active)){session=ReviewSession.restore(reviews.get(state.active),model);lastResult=session.events.length?session.assess(session.events.at(-1)):null;}}catch{}
 window.receiveNative=receiveNative;
 window.NativeReview.ready();
}
function renderReviews(){persistReviews();$('#review-list').innerHTML=[...reviews.values()].reverse().map(r=>'<button class="card review-summary" data-review-id="'+escape(r.session_id)+'"><strong>'+escape(r.claimed_org?.toUpperCase()||'Private review')+'</strong><span>'+r.events.length+' events · '+escape(r.workflow_state)+' · '+escape(r.payment_status.replaceAll('_',' '))+'</span><small>'+new Date(r.started).toLocaleString()+'</small></button>').join('')||'<div class="card"><h2>No reviews yet.</h2><p>Your checks and flagged calls will appear here.</p></div>';$$('[data-review-id]').forEach(b=>b.onclick=()=>{persistReviews();session=ReviewSession.restore(reviews.get(b.dataset.reviewId),model);lastResult=session.events.length?session.assess(session.events.at(-1)):null;$('#alert-card').hidden=!lastResult||!['high','warning'].includes(lastResult.severity);$('#alert-title').textContent='STOP & VERIFY';$('#alert-reason').textContent=lastResult?.reason||'';$('#sharing-consent').checked=false;render();view('protect');});}
function renderReviewDetails(){
 $('#active-review-label').textContent='Review '+session.id.slice(0,6)+(session.user_flagged?' · call flagged':'');
 $('#action-center').hidden=!(session.events.length||session.user_flagged);
 const v=lastResult?.verification;$('#verification-evidence').innerHTML=(session.timeline.some(e=>e.verification==='mismatch')?'<p class="verification-status">Earlier domain mismatch in this review. Caller identity is unverified.</p>':'')+(v?'<div class="eyebrow">CLAIMED IDENTITY</div><h3>'+escape(v.claimed_name)+'</h3><span class="verification-status">'+escape(v.status.toUpperCase())+' · DOMAIN CHECK</span><p>'+escape(v.explanation)+'</p>'+v.domains.map(d=>'<div class="domain-evidence">'+escape(d.domain)+' · '+escape(d.status)+'</div>').join('')+'<p class="help">Caller: unverified · Contact context: '+escape(v.sender_context)+' · Support contact: '+escape(v.support_contact)+' · Destination: '+escape(v.destination_type)+'</p><h3>Manipulation evidence</h3><p>'+escape(lastResult.manipulation?.map(e=>e.label).join(' · ')||'No manipulation evidence in this event.')+'</p><h3>Workflow risk</h3>':session.events.length?'<p>Review restored from derived signals. Caller identity remains unverified.</p>':'');
 if(session.payment_status!=='unknown')showResponse(session.payment_status==='sent'?'yes':'no',false);else $('#response-plan').replaceChildren();
 persistReviews();
}
function newReview(){persistReviews();session=new ReviewSession(model);lastResult=null;if(!pendingShared)$('#content').value='';$('#alert-card').hidden=true;$('#sharing-consent').checked=false;$('#sharing-status').textContent='';render();view('protect');}
$('#new-review').onclick=newReview;$('#reviews-new').onclick=newReview;
$('#quick-signals').innerHTML=QUICK_SIGNALS.map(([key,label])=>'<label class="check-label"><input type="checkbox" value="'+key+'"> '+escape(label)+'</label>').join('');
function openCall(details={}){if(details.id&&details.id!==session.id){persistReviews();session=reviews.has(details.id)?ReviewSession.restore(reviews.get(details.id),model):new ReviewSession(model);lastResult=null;}session.startCall(details);$('#quick-signals').querySelectorAll('input').forEach(i=>i.checked=false);render();view('protect');$('#call-dialog').showModal();}
$('#review-call').onclick=()=>openCall();$('#close-call').onclick=()=>$('#call-dialog').close();
$('#call-signals').onsubmit=e=>{e.preventDefault();const chosen=$$('#quick-signals input:checked').map(i=>i.value);check({channel:'call',text:signalText(chosen)||'Call reviewed; no listed signals noticed.'});$('#call-dialog').close();if(heroStep===2){heroStep=3;showHero();}};
function showResponse(paid,record=true){const plan=record?session.choosePayment(paid):responsePlan(paid);$('#response-plan').innerHTML='<h3>'+escape(plan.title)+'</h3><ol>'+plan.steps.map(s=>'<li>'+escape(s)+'</li>').join('')+'</ol><div class="response-links">'+plan.routes.map(r=>'<a class="outline" href="'+r.url+'" target="_blank" rel="noopener noreferrer" data-route="'+r.id+'">'+escape(r.label)+'</a>').join('')+'</div>';$$('[data-route]').forEach(a=>a.onclick=e=>{session.recordAction('report_route');persistReviews();if(window.NativeReview){e.preventDefault();window.NativeReview.openRoute(a.dataset.route);}});if(record)persistReviews();}
$('#paid-no').onclick=()=>showResponse('no');$('#paid-yes').onclick=()=>showResponse('yes');
$('#independent-verify').onclick=()=>{session.recordAction('verify_independently');persistReviews();toast('End the call. Use the bank app you already use, your bank card or branch. Do not use contact details in the suspicious message.');};
$('#block-ignore').onclick=()=>{session.recordAction('block_ignore');persistReviews();toast('Preserve needed evidence, then use Block in your phone or messaging app. AI-Protect has not blocked anyone.');};
$('#report-review').onclick=()=>view('privacy');
function exportReview(){session.recordAction('export');persistReviews();download('scamguard-redacted-review.json',{prototype:true,review:session.snapshot(),fingerprint:session.fingerprint(),note:'Derived signals only. Preserve original receipts and messages separately.'});}
$('#save-review').onclick=exportReview;$('#delete-review').onclick=reset;
let heroStep=-1;
const heroCopy=['A message claims HDFC Bank: “Update KYC immediately or your account will be blocked. https://hdfc-kyc.example.invalid/verify”. Tap to check this synthetic message.','The message used a domain outside the bank registry. Now an incoming caller claims to be the KYC desk. Nothing from this call is analyzed until you tap Review.','Select what the caller asked for. In this demo: bank claim, urgency, and money.','A WhatsApp message follows: “Stay on the call. Transfer to a safe account using https://hdfc-kyc.example.invalid/pay”.','The caller sends an outgoing UPI QR. It prepares ₹4,500 to a new beneficiary. No money can move in this demo.'];
function showHero(){$('#hero-copy').textContent=heroCopy[heroStep]||'Review the timeline and choose whether money was sent.';$('#hero-next').textContent=heroStep===1?'🛡 Review this call':heroStep===4?'Check outgoing QR':'Check next event';$('#hero-dialog').showModal();}
$('#hero-demo').onclick=()=>{newReview();heroStep=0;showHero();};
$('#hero-close').onclick=()=>{$('#hero-dialog').close();heroStep=-1;};
$('#hero-next').onclick=()=>{$('#hero-dialog').close();if(heroStep===0){check({channel:'message',text:'HDFC Bank: Update KYC immediately or your account will be blocked. https://hdfc-kyc.example.invalid/verify'});heroStep=1;showHero();}else if(heroStep===1){heroStep=2;openCall({direction:'incoming'});}else if(heroStep===3){check({channel:'message',text:'Stay on the call. Transfer to a safe account using https://hdfc-kyc.example.invalid/pay'});heroStep=4;showHero();}else if(heroStep===4){check({channel:'qr',text:'upi://pay?pa=kyc-demo@demo&am=4500&cu=INR'});heroStep=-1;$('#action-center').scrollIntoView({block:'start'});}};
$('#normal-demo').onclick=()=>{newReview();check({channel:'call',text:'Your grocery order is ready for pickup.'});check({channel:'qr',text:'upi://pay?pa=grocery@demo&am=450&cu=INR'});check({channel:'payment',payment:{amount:450,newPayee:false}});toast('Ordinary purchase: no warning triggered. Identity is still not authenticated.');};
async function receiveNative(payload){
 if(payload.kind==='call'){openCall({id:payload.id,direction:payload.direction});return;}
 if(payload.kind==='postcall'){view('protect');$('#action-center').hidden=false;$('#action-center').scrollIntoView({block:'start'});return;}
 if(payload.kind==='share'){
  view('protect');setChannel(String(payload.text||'').trim().startsWith('upi://')?'qr':'message');pendingShared=true;pendingEvidenceType=null;$('#content').value=String(payload.text||'').slice(0,10000);
  if(payload.image){pendingEvidenceType='screenshot';try{const bytes=Uint8Array.from(atob(payload.image),c=>c.charCodeAt(0));const value=await decodeImage(new Blob([bytes],{type:payload.mime||'image/png'}));setChannel(value.startsWith('upi://')?'qr':'message');$('#content').value=value;}catch{$('#content').value='Screenshot supplied by user; no readable QR. Contents not analyzed.';toast('No readable QR. Tap Check to record screenshot evidence only, or replace this text with relevant words. Keep the original image yourself.');return;}}
  toast('Shared content is ready for review '+session.id.slice(0,6)+'. Tap Check to associate it, or New review for another request.');
 }
}
