import {Session,parseUPI} from '/core/engine.mjs';
import {scenarios} from '/simulator/scenarios.mjs';
import {Analytics} from '/web/analytics.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let model=null;try{model=await(await fetch('/core/model.json')).json();}catch{}
const session=new Session(model),analytics=new Analytics();let channel='message',selected=scenarios[0],step=0,lastResult=null,lastLatency=0,toastTimer,sharedId=null,replayBusy=false;
const names={protect:'Protection desk',lab:'Scenario lab',campaigns:'Campaign inbox',evaluation:'Validation',privacy:'Privacy controls'};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function view(name){for(const v of $$('.view'))v.hidden=v.id!=='view-'+name;for(const b of $$('[data-view]'))b.classList.toggle('active',b.dataset.view===name);$('#page-name').textContent=names[name];if(name==='privacy')renderFingerprint();if(name==='campaigns')refreshCampaigns();if(name==='evaluation')evaluation();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function reset(){session.reset();lastResult=null;step=0;$('#content').value='';$('#payee').value='';$('#form-error').textContent='';$('#sharing-consent').checked=false;$('#sharing-status').textContent='';$('#alert-card').hidden=true;$('#decision-result').textContent='';$('#replay-output').replaceChildren();render();renderScenario();toast('Session cleared. Local checks are ready.');}
$('#clear-session').onclick=reset;$('#privacy-clear').onclick=reset;
const help={message:['Paste a message you want to check','Only content you submit is checked. Text is cleared after analysis.','Your refund is ready. Scan this QR to receive money…'],link:['Paste a suspicious link','The link is inspected as text. ScamGuard never opens the destination.','https://example.invalid/support.apk'],qr:['Paste the decoded UPI QR payload','An upi://pay intent sends money. Payee details are parsed locally and discarded.','upi://pay?pa=merchant@demo&am=2500&cu=INR'],call:['Paste a consented call transcript','Typed transcript only. This prototype does not listen to calls or request microphone access.','I am a police officer. Do not disconnect. Transfer to a safe account.']};
function setChannel(c){channel=c;for(const b of $$('[data-channel]')){b.classList.toggle('selected',b.dataset.channel===c);b.setAttribute('aria-selected',String(b.dataset.channel===c));}$('#payment-input').hidden=c!=='payment';$('#text-input').hidden=c==='payment';$('#qr-import').hidden=c!=='qr';$('#form-error').textContent='';if(help[c]){$('#input-label').textContent=help[c][0];$('#input-help').textContent=help[c][1];$('#content').placeholder=help[c][2];}$('#content').value='';}
$$('[data-channel]').forEach(b=>b.onclick=()=>setChannel(b.dataset.channel));
function check(input){const start=performance.now();const r=session.add(input);lastLatency=performance.now()-start;lastResult=r;render();if(r.showWarning){$('#alert-card').hidden=false;$('#alert-title').textContent='This request needs a pause.';$('#alert-reason').textContent=r.reason;$('#decision-result').textContent='';analytics.capture('warning_shown',{severity:r.severity,stage:r.stage,latency_ms:lastLatency});}return r;}
$('#check-form').onsubmit=ev=>{ev.preventDefault();try{let input={channel,text:$('#content').value};if(channel==='payment')input={channel,payment:{amount:Number($('#amount').value),newPayee:$('#new-payee').checked}};else if(!input.text.trim())throw Error('Paste content before checking.');check(input);$('#content').value='';$('#payee').value='';$('#form-error').textContent='';toast(lastResult.showWarning?'Pause and verify this request.':'Context checked locally.');}catch(e){$('#form-error').textContent=e.message;}};
function render(){const count=session.events.length;$('#event-count').textContent=count+' event'+(count===1?'':'s');$('#session-empty').hidden=count>0;$('#session-result').hidden=!count;$('#export-session').disabled=!count;if(lastResult){$('#evidence').innerHTML=lastResult.evidenceScore+'<span>/100</span>';$('#risk').innerHTML=lastResult.actionRisk+'<span>/100</span>';$('#risk-bar').style.width=lastResult.actionRisk+'%';$('#stage').textContent=lastResult.stage;$('#severity').textContent=lastResult.suppressed?'Repeated warning limited':lastResult.severity.toUpperCase();$('#result-note').textContent=lastResult.reason;$('#latency').textContent='Last local check: '+lastLatency.toFixed(1)+' ms';$('#timeline').innerHTML=session.events.map((e,i)=>'<div class="timeline-item"><strong>'+String(i+1).padStart(2,'0')+' / '+escape(e.channel.toUpperCase())+'</strong><span>'+escape(e.tactics.join(' · ')||'No tactic evidence')+'</span></div>').join('');}else{$('#timeline').replaceChildren();$('#latency').textContent='Waiting for your first check';}renderFingerprint();}
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#export-session').onclick=()=>download('scamguard-redacted-report.json',{prototype:true,fingerprint:session.fingerprint(),assessment:lastResult?{family:lastResult.family,severity:lastResult.severity,stage:lastResult.stage,reason:lastResult.reason}:null});
$('#cancel-payment').onclick=()=>{$('#decision-result').textContent='Simulated request cancelled. No money has moved.';analytics.capture('user_cancelled_payment',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#continue-payment').onclick=()=>$('#continue-dialog').showModal();$('#keep-paused').onclick=()=>$('#continue-dialog').close();$('#confirm-continue').onclick=()=>{$('#continue-dialog').close();$('#decision-result').textContent='Simulated request continued by your choice. No real transaction occurred.';analytics.capture('user_continued',{severity:lastResult?.severity,stage:lastResult?.stage});};
$('#false-positive').onclick=()=>{$('#decision-result').textContent='Feedback recorded for this visit. The detection policy has not been changed.';analytics.capture('false_positive_feedback',{severity:lastResult?.severity,stage:lastResult?.stage});};
function renderScenarios(){$('#scenario-list').innerHTML=scenarios.map(s=>'<button class="scenario-item '+(s.id===selected.id?'active':'')+'" data-scenario="'+s.id+'"><span>'+(s.scam?'SCAM SIMULATION':'ORDINARY WORKFLOW')+(s.holdout?' · HOLDOUT':'')+'</span><strong>'+escape(s.name)+'</strong></button>').join('');$$('[data-scenario]').forEach(b=>b.onclick=()=>{if(replayBusy)return;selected=scenarios.find(s=>s.id===b.dataset.scenario);reset();renderScenarios();});}
function renderScenario(){$('#scenario-type').textContent=selected.scam?'SYNTHETIC SCAM SCENARIO':'SYNTHETIC ORDINARY WORKFLOW';$('#scenario-name').textContent=selected.name;$('#scenario-description').textContent=selected.description;$('#step-count').textContent=step+' / '+selected.events.length;const e=selected.events[step];$('#replay-preview').innerHTML=e?'<small>NEXT / '+escape(e.channel.toUpperCase())+'</small><p>'+escape(e.payment?'Prepare a simulated ₹'+e.payment.amount.toLocaleString('en-IN')+' transfer'+(e.payment.newPayee?' to a new beneficiary.':'.'):e.text)+'</p>':'<small>STORY COMPLETE</small><p>'+(selected.scam?'Review the warning and evidence at the protection desk.':'An ordinary workflow checked without inventing a scam verdict.')+'</p>';$('#next-event').disabled=!e;$('#run-all').disabled=!e;}
function next(){if(step>=selected.events.length)return;const r=check({...selected.events[step],timestamp:session.started-(selected.events.length-step)*20000});step++;const div=document.createElement('div');div.className='replay-result'+(r.showWarning?' warning':'');div.innerHTML='<b>'+step+' / '+escape(r.event.channel.toUpperCase())+' · '+(r.showWarning?'WARNING':r.suppressed?'REPEAT LIMITED':r.severity.toUpperCase())+'</b><br>'+escape(r.reason);$('#replay-output').append(div);renderScenario();}
$('#next-event').onclick=next;$('#run-all').onclick=()=>{replayBusy=true;try{while(step<selected.events.length)next();}finally{replayBusy=false;}};$('#restart-demo').onclick=reset;$('#try-demo').onclick=()=>{selected=scenarios[0];reset();renderScenarios();view('lab');};$('#open-desk').onclick=()=>view('protect');
async function api(path,body,method='POST',headers={}){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const p=await r.json();if(!r.ok)throw Error(p.error||'Request failed');return p;}
function renderFingerprint(){$('#fingerprint-preview').textContent=JSON.stringify(session.fingerprint(),null,2);}
$('#share-pattern').onclick=async()=>{try{if(!$('#sharing-consent').checked)throw Error('Choose to share this pattern first.');if(!session.events.length)throw Error('Check at least one event first.');await api('/api/fingerprints',{consent:true,fingerprint:session.fingerprint()});sharedId=session.id;$('#sharing-status').textContent='Shared with the local campaign service. Retained for at most 24 hours.';analytics.capture('user_reported_scam');}catch(e){$('#sharing-status').textContent=e.message;}};
$('#delete-pattern').onclick=async()=>{try{if(!sharedId)throw Error('No pattern has been shared during this visit.');await api('/api/fingerprints/'+encodeURIComponent(sharedId),null,'DELETE');sharedId=null;$('#sharing-status').textContent='Your shared pattern was deleted.';}catch(e){$('#sharing-status').textContent=e.message;}};
$('#analytics-consent').onchange=async()=>{await analytics.load();analytics.enable($('#analytics-consent').checked);if(!analytics.enabled)$('#analytics-consent').checked=false;$('#analytics-status').textContent=analytics.enabled?'Anonymous usage events enabled for this visit.':'Analytics are off. The operator must configure a PostHog project token to enable them.';if(analytics.enabled)analytics.capture('scamguard_activated');};
async function refreshCampaigns(){try{const {campaigns}=await(await fetch('/api/campaigns')).json();$('#campaign-list').innerHTML=campaigns.length?campaigns.map(g=>'<section class="card campaign-card"><div><div class="eyebrow">'+escape(g.status.toUpperCase())+' · UNVERIFIED REPORTS</div><h2>Repeated workflow candidate</h2><div class="chips">'+g.tactics.map(t=>'<span>'+escape(t)+'</span>').join('')+'</div><p>'+escape(g.method)+'. Similar tactic sets, not verified identities. No payee data collected.</p><div class="review-actions"><button class="outline" data-review="reviewed" data-signature="'+escape(g.signature)+'">Mark reviewed</button> <button class="text-button" data-review="dismissed" data-signature="'+escape(g.signature)+'">Dismiss candidate</button></div></div><div class="campaign-count">'+g.reports+'<small>CONSENTED PATTERNS</small></div></section>').join(''):'<div class="card"><h2>No candidates yet.</h2><p>Share consenting test-session patterns, or generate synthetic reports. Three similar reports create a candidate for review.</p></div>';$$('[data-review]').forEach(b=>b.onclick=async()=>{try{await api('/api/review',{signature:b.dataset.signature,status:b.dataset.review},'POST',{Authorization:'Bearer '+$('#review-token').value});$('#review-token').value='';refreshCampaigns();toast('Candidate review saved. No threat policy was published.');}catch(e){toast(e.message);}});}catch{$('#campaign-list').innerHTML='<div class="card"><h2>The campaign service is unavailable.</h2><p>Local protection still works. Start the Python server to review patterns.</p></div>';}}
$('#refresh-campaigns').onclick=refreshCampaigns;$('#seed-campaigns').onclick=async()=>{try{for(let i=0;i<5;i++){const s=new Session(model);const scenario=scenarios.find(s=>s.id==='investment');for(const [j,e] of scenario.events.entries())s.add({...e,timestamp:s.started+j*20000});await api('/api/fingerprints',{consent:true,fingerprint:s.fingerprint()});}$('#campaign-status').textContent='5 AI-authored synthetic session fingerprints added.';refreshCampaigns();}catch(e){$('#campaign-status').textContent=e.message;}};
async function evaluation(){try{const m=await(await fetch('/evaluation/results.json')).json();$('#evaluation-content').innerHTML='<div class="metrics-grid">'+[['Scam workflows warned',m.true_positive+'/'+m.scam_sessions,'Synthetic workflow recall'],['Legitimate interruptions',m.false_positive+'/'+m.legitimate_sessions,'Synthetic benign flows'],['Pre-payment coverage',Math.round(m.prepayment_rate*100)+'%','Only payment scam scenarios'],['P95 engine latency',m.latency_ms.p95.toFixed(2)+' ms',m.environment]].map(([a,b,c])=>'<div class="card metric-card"><span class="metric-label">'+escape(a)+'</span><strong>'+escape(b)+'</strong><p>'+escape(c)+'</p></div>').join('')+'</div><div class="card table-scroll"><table><caption>Every workflow, disclosed</caption><thead><tr><th>SCENARIO</th><th>EXPECTED</th><th>WARNING</th><th>FIRST WARNING STAGE</th></tr></thead><tbody>'+m.scenarios.map(s=>'<tr><td>'+escape(s.name)+'</td><td>'+(s.scam?'Scam':'Ordinary')+'</td><td>'+(s.warned?'Yes':'No')+'</td><td>'+escape(s.first_warning_stage||'—')+'</td></tr>').join('')+'</tbody></table><p class="help">Generated '+escape(m.generated_at)+'. Scores are deterministic heuristic indices. The 157-text model is experimental support only. The workflow engine makes the warning decision.</p></div>';}catch{$('#evaluation-content').innerHTML='<div class="card"><p>Run npm run evaluate to produce the reproducible evaluation report.</p></div>';}}
$('#qr-file').onchange=async ev=>{const file=ev.target.files[0];try{if(!file)return;if(file.size>5*1024*1024)throw Error('Use an image under 5 MB.');if(!('BarcodeDetector' in window))throw Error('QR image reading is not supported in this browser. Paste a decoded UPI payload instead.');const bitmap=await createImageBitmap(file);try{const detector=new BarcodeDetector({formats:['qr_code']});const codes=await detector.detect(bitmap);if(codes.length!==1)throw Error('Use an image containing exactly one QR code.');parseUPI(codes[0].rawValue);$('#content').value=codes[0].rawValue;toast('QR decoded locally. Tap Check to inspect the payment intent.');}finally{bitmap.close();}}catch(e){$('#form-error').textContent=e.message;}finally{ev.target.value='';}};
render();renderScenarios();renderScenario();
window.addEventListener('offline',()=>$('#connectivity').textContent='● Offline local checks');window.addEventListener('online',()=>$('#connectivity').textContent='● On-device engine');
if('serviceWorker' in navigator)navigator.serviceWorker.register('/web/sw.js',{scope:'/'}).catch(()=>{});
